"""test3

Revision ID: 18e69630003f
Revises: d1d9426e1da5
Create Date: 2024-08-01 01:16:22.950603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e69630003f'
down_revision = 'd1d9426e1da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('test_user_usernamee_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('usernamee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usernamee', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('test_user_usernamee_key', ['usernamee'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
