"""empty message

Revision ID: d786d62ec9b8
Revises: 078cf3505e3b
Create Date: 2024-08-12 03:14:14.251055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd786d62ec9b8'
down_revision = '078cf3505e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('auto_reply_delay', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auto_reply_delay')
        batch_op.drop_column('auto_reply_enabled')

    # ### end Alembic commands ###
