"""test1

Revision ID: dd0b637da609
Revises: 6c233d272097
Create Date: 2024-08-01 01:09:57.994768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0b637da609'
down_revision = '6c233d272097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usernamee', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_user_pkey'),
    sa.UniqueConstraint('usernamee', name='test_user_usernamee_key')
    )
    # ### end Alembic commands ###
