"""update post

Revision ID: ddc2340e2872
Revises: 8511e344ad6b
Create Date: 2024-08-06 18:10:02.934173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc2340e2872'
down_revision = '8511e344ad6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
